const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_SHOW_NAV: 'CHANGE_SHOW_NAV',
    CHANGE_CURRENT_TAG: 'CHANGE_CURRENT_TAG',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    GET_ORDERS_BY_STATUS: 'GET_ORDERS_BY_STATUS',
    GET_VEHICLES_BY_IDTRANSPORTER: 'GET_VEHICLES_BY_IDTRANSPORTER',
    GET_SERVICE_OF_IDTRANSPORTER: 'GET_SERVICE_OF_IDTRANSPORTER',
    GET_SCOPE_OF_IDTRANSPORTER: 'GET_SCOPE_OF_IDTRANSPORTER',
    GET_DRIVERS_BY_IDTRANSPORTER: 'GET_DRIVERS_BY_IDTRANSPORTER',
})

export default actionTypes;